### PR TITLE
Updating sidecar config

### PR DESCRIPTION
**Pull request by glennblock**
Updating topaz-config to use newer format. Added a new zip file for simplicity so all files can be downloaded at once.

### CODE REVIEW

**Review by apoland — APPROVED** [review]

**Comment by apoland** [comment]
@glennblock It might be helpful if we could actually put this config in the topaz repo and link directly to that, so that developers would be able to see it and update it when the config changes.  As a zip file in the web site repo there's less chance that this will get seen and updated.

**Comment by glennblock** [comment]
Ah you mean move it to the repo itself? I'll do that.

As to the zip maybe we can have a yarn build step to build it? Having
downloaded the initial files, it is a lot less awkward with a zip.

**Comment by apoland** [comment]
Right on, yeah we can come up with a process to build and release the zip file.

**Comment by glennblock** [comment]
OK, i'll close the PR and re-open in Topaz, then we can update Aserto and Topaz docs.

**Pull request closed without merging**
